apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-ip.yml convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dota2parser
  name: dota2parser
spec:
  ports:
    - name: "5600"
      port: 5600
      targetPort: 5600
  clusterIP: 10.96.0.3
  externalIPs:
    - 10.41.32.160
  selector:
    io.kompose.service: dota2parser
status:
  loadBalancer: {}
